### ISSUE TITLE
No need to increment value of ip or workers if we only need their count

### ISSUE THREAD

**Issue by mariosky** [NodeoIO/NodIO#13]
On the code:
if ( !IPs[ client_ip ] ) {
IPs[ client_ip ]=1;
} else {
IPs[ client_ip ]++;
}
Why keep a counter of requests by IP? This info is on the log any way. 
Propose to change like:
if ( !IPs[ client_ip ] ) {
IPs[ client_ip ]=1;

**Comment by JJ** [comment]
We do it just in case... But it's true, we don't log it...
