### ISSUE TITLE
Usar librerías para Ajax

### ISSUE THREAD

**Issue by JJ** [NodeoIO/NodIO#6]
Crear los xhr directamente no es muy elegante. ¿Se podría usar [twix](https://github.com/neilco/twix), por ejemplo?

**Comment by mariosky** [comment]
Me parece bien.

2015-10-05 4:15 GMT-07:00 Juan Julián Merelo Guervós <
notifications@github.com>:

**Comment by JJ** [comment]
De todas formas, igual deberíamos hacer Ajax desde el "host" y no desde el
worker... usar el worker sólo para el algoritmo genético, como te he
comentado en el email.

**Comment by mariosky** [comment]
Si se hace asi, ¿No se detendria al perder el focus la pagina?

**Comment by JJ** [comment]
El 5 de octubre de 2015, 19:19, Mario Garcia Valdez <
notifications@github.com> escribió:

> Si se hace asi, ¿No se detendria al perder el focus la pagina?

Es cierto. OK, se hace desde el worker entonces

**Comment by mariosky** [comment]
Fixed in 5900be33fbc4e81d7a51a10ebe9309ab11c88b13

**Comment by JJ** [comment]
Great job, Mario.

2015-10-09 18:52 GMT+02:00 Mario Garcia Valdez notifications@github.com:

> Fixed in 5900be3
> https://github.com/NodeoIO/NodIO/commit/5900be33fbc4e81d7a51a10ebe9309ab11c88b13
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NodeoIO/NodIO/issues/6#issuecomment-146928844.

## 

JJ
