### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by mariosky** [NodeoIO/NodIO#8]
I'm getting an "Uncaught SyntaxError: Unexpected end of input"
When parsing results like:
 JSON.parse(xmlhttp2.responseText)  

Maybe the response  .send({ current_expid: sequence });  
is not proper JSON?

**Comment by mariosky** [comment]
Voy a revisar el Response en DeveloperTools

**Comment by JJ** [comment]
Maybe. I'll check it out.

**Comment by JJ** [comment]
This is the response:

```
NodIO git:(master) ✗ curl -X PUT http://localhost:5555/experiment/1/one/1111111111111111000011111111111111111111000011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111000011111111/77/UUID
{
  "current_expid": 0
}%     
```

Maybe the 410 is a problem?

**Comment by mariosky** [comment]
Is fine, is on my side.
 I was reading before readyState == 4
